### ISSUE TITLE
Optimized VPK folder prevents Titanfall 2 dedicated server from starting

### ISSUE THREAD

**Issue by codylc** [pg9182/tf2vpk#1]
A little over my skis compiling a go app, but I believe there's an issue with the VPKs after optimizing them for a Titanfall 2 docker server. I've followed the instructions [here ](https://github.com/pg9182/northstar-dedicated#system-requirements)to remove unnecessary VPK files.

After compiling tf2-vpkoptim I ran the following to prep the VPK folder:
`tf2-vpkoptim ~/games/Titanfall2/vpk \
    --verbose \
    --merge \
    --exclude '*.vtf' \
    --exclude '/depot' \
    --exclude '*.bsp_lump' \
    --output ~/games/vpk`

When I swapped the vpk directories and started the docker container, I receive the following error before it reattempts to start again:
`Unable to load manifest file 'scripts/surfaceproperties_manifest.txt'`

Swap the vpk folder back to the original directory and the server loads successfully.

Providing more logs below for context. As an aside, would be really helpful if you could add a compiled binary to the releases in the future, though ChatGPT carried me this far. Thanks in advance!

> [03:11:30] [NORTHSTAR] [info] Host_Init()
> 0024:fixme:thread:SetThreadIdealProcessor (FFFFFFFFFFFFFFFE 0): stub
> 0024:fixme:thread:SetThreadIdealProcessor (00000000000002E0 2): stub
> 0024:fixme:thread:SetThreadIdealProcessor (00000000000002FC 4): stub
> 0024:fixme:thread:SetThreadIdealProcessor (0000000000000318 6): stub
> [03:11:30] [RPAK_FSYS] [info] LoadPakAsync common.rpak 1
> [03:11:30] [RPAK_FSYS] [info] Not loading pak ./R2Northstar\mods\Northstar.Custom\paks\mp_weapon_shotgun_doublebarrel.rpak for dedicated server
> [03:11:31] [RPAK_FSYS] [info] Not loading pak ui.rpak for dedicated server
> [03:11:31] [RPAK_FSYS] [info] Not loading pak particle_scripts.rpak for dedicated server
> [03:11:31] [RPAK_FSYS] [info] Not loading pak highlight.rpak for dedicated server
> [03:11:31] [RPAK_FSYS] [info] Not loading pak mp_lobby.rpak for dedicated server
> [03:11:31] [RPAK_FSYS] [info] Not loading pak mp_lobby_loadscreen.rpak for dedicated server
> [03:11:32] [NORTHSTAR] [info] [DEDICATED SERVER] FatalError:
> [03:11:32] [NORTHSTAR] [info] [DEDICATED SERVER] Unable to load manifest file 'scripts/surfaceproperties_manifest.txt'
> Unable to load manifest file 'scripts/surfaceproperties_manifest.txt'
> nswrap: northstar exited with status 18
> nswrap: killing xvfb
> nswrap: waiting for children to exit

**Comment by pg9182** [comment]
I haven't seen that before, but try following everything here too: https://github.com/pg9182/northstar-dedicated#reducing-the-size-.

**Comment by codylc** [comment]
Sorry, didn't want to distract from the VPK files but yes, I had followed all the steps to remove the files suggested there. The TF2 directory works great with those files removed. It's only when I use tf2-vpkoptim and introduce the new VPK directory that things error out.

**Comment by pg9182** [comment]
I cannot reproduce this issue with my old build nor with another one from scratch.
